### ISSUE TITLE
Use of apparmor within containerd ?

### ISSUE THREAD

**Issue by kkaempf** [rancher/image-build-containerd#22]
Why is `containerd` built [with apparmor](https://github.com/rancher/image-build-containerd/blob/f2f1c48de5561b32fcced2d7546fb5e7482235da/Dockerfile#L36) enabled ?

This requires us to [add apparmor-parser](https://github.com/rancher/elemental/issues/349) to the Elemental image.

But since Elemental is based on SLE Micro for Rancher, this is a supportability problem.

/cc @agracey @pgonin

**Comment by brandond** [comment]
This is not a SLE-specific build. It is used on all distros, including RHEL and Ubuntu. We build with the common set of features that will be used across all platforms.
